import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

export interface PayslipPdfInput {
  companyName: string;
  employeeName: string;
  employeeNo?: string | null;
  periodLabel: string;
  grossEarnings: number;
  employeeDeductions: number;
  employerContributions: number;
  netPay: number;
  epfEmployee: number;
  epfEmployer: number;
  etfEmployer: number;
  apit: number;
  lines: Array<{ code: string; name: string; amount: number; type: string }>;
}

@Injectable()
export class PayrollPdfService {
  async createPayslip(input: PayslipPdfInput): Promise<Buffer> {
    const doc = new PDFDocument({ margin: 48, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    const done = new Promise<Buffer>((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });

    doc.fontSize(18).text(input.companyName, { align: 'center' });
    doc.moveDown(0.4);
    doc.fontSize(14).text('Payslip', { align: 'center' });
    doc.fontSize(10).text(input.periodLabel, { align: 'center' });
    doc.moveDown();
    doc.fontSize(11).text(`Employee: ${input.employeeName}`);
    if (input.employeeNo) doc.text(`Employee No: ${input.employeeNo}`);
    doc.moveDown();

    this.row(doc, 'Gross Earnings', input.grossEarnings);
    this.row(doc, 'Employee Deductions', input.employeeDeductions);
    this.row(doc, 'Net Pay', input.netPay, true);
    doc.moveDown();

    doc.fontSize(12).text('Breakdown', { underline: true });
    doc.moveDown(0.4);
    for (const line of input.lines) {
      this.row(doc, `${line.name} (${line.code})`, line.amount);
    }

    doc.moveDown();
    doc.fontSize(12).text('Statutory Summary', { underline: true });
    doc.moveDown(0.4);
    this.row(doc, 'APIT', input.apit);
    this.row(doc, 'EPF Employee', input.epfEmployee);
    this.row(doc, 'EPF Employer', input.epfEmployer);
    this.row(doc, 'ETF Employer', input.etfEmployer);
    this.row(doc, 'Employer Contributions', input.employerContributions, true);

    doc.moveDown();
    doc
      .fontSize(8)
      .fillColor('gray')
      .text('Generated by HR System. Amounts are shown in LKR.');
    doc.end();

    return done;
  }

  private row(
    doc: PDFKit.PDFDocument,
    label: string,
    amount: number,
    bold = false,
  ) {
    const y = doc.y;
    doc.fontSize(10).fillColor('black');
    if (bold) doc.font('Helvetica-Bold');
    doc.text(label, 48, y, { width: 330 });
    doc.text(this.money(amount), 390, y, { width: 150, align: 'right' });
    if (bold) doc.font('Helvetica');
    doc.moveDown(0.35);
  }

  private money(value: number) {
    return `LKR ${Number(value).toLocaleString('en-LK', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;
  }
}
