import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

export interface TotalCompensationStatementInput {
  companyName: string;
  employeeName: string;
  employeeNo?: string | null;
  jobTitle?: string | null;
  department?: string | null;
  periodLabel: string;
  currency: string;
  baseSalary: number;
  annualizedBaseSalary: number;
  salaryComponents: Array<{ name: string; amount: number; quantity?: number }>;
  variablePay: Array<{ name: string; amount: number; status: string }>;
  allowances: Array<{ name: string; amount: number; period: string }>;
  benefits: Array<{
    name: string;
    employeeContribution: number;
    employerContribution: number;
    status: string;
  }>;
  totals: {
    annualCash: number;
    allowances: number;
    employerBenefits: number;
    totalCompensation: number;
  };
}

@Injectable()
export class CompensationPdfService {
  async createTotalCompensationStatement(
    input: TotalCompensationStatementInput,
  ): Promise<Buffer> {
    const doc = new PDFDocument({ margin: 48, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    const done = new Promise<Buffer>((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });

    doc.fontSize(18).text(input.companyName, { align: 'center' });
    doc.moveDown(0.35);
    doc.fontSize(14).text('Total Compensation Statement', { align: 'center' });
    doc.fontSize(10).text(input.periodLabel, { align: 'center' });
    doc.moveDown();

    doc.fontSize(11).text(`Employee: ${input.employeeName}`);
    if (input.employeeNo) doc.text(`Employee No: ${input.employeeNo}`);
    if (input.jobTitle) doc.text(`Job Title: ${input.jobTitle}`);
    if (input.department) doc.text(`Department: ${input.department}`);
    doc.moveDown();

    this.section(doc, 'Summary');
    this.row(doc, 'Monthly base salary', input.baseSalary, input.currency);
    this.row(
      doc,
      'Annualized base salary',
      input.annualizedBaseSalary,
      input.currency,
    );
    this.row(
      doc,
      'Annual cash compensation',
      input.totals.annualCash,
      input.currency,
    );
    this.row(doc, 'Allowances', input.totals.allowances, input.currency);
    this.row(
      doc,
      'Employer-paid benefits',
      input.totals.employerBenefits,
      input.currency,
    );
    this.row(
      doc,
      'Estimated total compensation',
      input.totals.totalCompensation,
      input.currency,
      true,
    );
    doc.moveDown();

    this.table(
      doc,
      'Salary Components',
      ['Component', 'Amount'],
      input.salaryComponents.map((item) => [
        item.quantity ? `${item.name} x ${item.quantity}` : item.name,
        this.money(item.amount, input.currency),
      ]),
    );
    this.table(
      doc,
      'Bonus and Variable Pay',
      ['Award', 'Amount'],
      input.variablePay.map((item) => [
        `${item.name} (${item.status})`,
        this.money(item.amount, input.currency),
      ]),
    );
    this.table(
      doc,
      'Allowances',
      ['Allowance', 'Approved'],
      input.allowances.map((item) => [
        `${item.name} - ${item.period}`,
        this.money(item.amount, input.currency),
      ]),
    );
    this.table(
      doc,
      'Benefits',
      ['Benefit', 'Employer Value'],
      input.benefits.map((item) => [
        `${item.name} (${item.status})`,
        this.money(item.employerContribution, input.currency),
      ]),
    );

    doc.moveDown();
    doc
      .fontSize(8)
      .fillColor('gray')
      .text(
        'Generated by HR System. This statement is informational and excludes statutory deductions unless shown in payroll.',
      );
    doc.end();

    return done;
  }

  private table(
    doc: PDFKit.PDFDocument,
    title: string,
    headers: [string, string],
    rows: string[][],
  ) {
    this.section(doc, title);
    this.textRow(doc, headers[0], headers[1], true);
    if (!rows.length) {
      this.textRow(doc, 'None recorded', '');
    } else {
      for (const row of rows) this.textRow(doc, row[0], row[1]);
    }
    doc.moveDown();
  }

  private section(doc: PDFKit.PDFDocument, label: string) {
    doc.font('Helvetica-Bold').fontSize(12).fillColor('black').text(label);
    doc.font('Helvetica');
    doc.moveDown(0.35);
  }

  private row(
    doc: PDFKit.PDFDocument,
    label: string,
    amount: number,
    currency: string,
    bold = false,
  ) {
    this.textRow(doc, label, this.money(amount, currency), bold);
  }

  private textRow(
    doc: PDFKit.PDFDocument,
    label: string,
    value: string,
    bold = false,
  ) {
    const y = doc.y;
    doc.fontSize(10).fillColor('black');
    if (bold) doc.font('Helvetica-Bold');
    doc.text(label, 48, y, { width: 330 });
    doc.text(value, 390, y, { width: 150, align: 'right' });
    if (bold) doc.font('Helvetica');
    doc.moveDown(0.35);
  }

  private money(value: number, currency: string) {
    return `${currency} ${Number(value).toLocaleString('en-LK', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;
  }
}
